import { format_time_duration } from "@beenotung/tslib";
import { DAY } from "@beenotung/tslib/time";
import { find } from "better-sqlite3-proxy";
import { db } from "../db";
import { autoParagraph, Email, sendEmail } from "../email";
import { env } from "../env";
import { proxy, TUser } from "../proxy";

// TODO send a long time no see promo email notice to do booking
// TODO use custom interval (e.g. 60 days)

type LastBookingRow = {
  user_id: number;
};

let select_last_booking = db.prepare(/* sql */ `
select
  user_id
, (
    select max(notice_time)
    from t_remind_booking
    where t_remind_booking.user_id = t_service_booking.user_id
  ) as last_notice_time
from t_service_booking
group by user_id
having max(to_time) < :cutoff_time
   and (
    max(to_time) > last_notice_time
    or
    last_notice_time is null
   )
`);

// TODO send these email in background
export function createRemindBookingEmail(user: TUser): Email {
  let interval_time =
    proxy.t_shop_setting[1]?.remind_booking_interval || 60 * DAY;
  let interval_day = Math.round(interval_time / DAY);
  return {
    to_email: user.email,
    subject: `[Booking Reminder] Reminder to Book Your Next Service Appointment`,
    html: /* html */ `
Dear ${user.username},

${autoParagraph(/* html */ `
We hope this email finds you well.
We wanted to remind you that it has been ${interval_day} days since your last booking to use our services.
We value your business and want to ensure that you continue to receive the best service possible.

To avoid any inconvenience, we suggest that you make a booking as soon as possible to secure your preferred date and time.
Our team is ready to assist you with any questions or concerns you may have, and we are committed to providing you with the highest level of service.

To make a booking, simply visit our <a href="${env.FRONTEND_ORIGIN}">website</a> or give us a call at <a href="tel:${env.COMPANY_PHONE}">${env.COMPANY_PHONE}</a>.
Our team will be happy to assist you and ensure that the booking process is smooth and hassle-free.

<p>
  <a href="${env.FRONTEND_ORIGIN}"><button style="
  border: 1px solid black;
  border-radius: 4px;
  box-shadow: 2px 2px 2px black;
  ">「立即預約」</button></a>
</p>


We appreciate your continued support and look forward to serving you again soon.
`)}

Best regards,<br>
<br>
${env.COMPANY_NAME}<br>
${env.COMPANY_PHONE}<br>
${env.EMAIL_ADDRESS}<br>

<p>
  P.S. This email is automatically generated by the system. Direct reply to this email may not be received.
</p>
`.trim(),
  };
}

export async function sendRemindBookingEmails() {
  let interval_time =
    proxy.t_shop_setting[1]?.remind_booking_interval || 60 * DAY;
  let rows = select_last_booking.all({
    cutoff_time: Date.now() - interval_time,
  }) as LastBookingRow[];
  for (let row of rows) {
    let user = proxy.t_user[row.user_id];
    let email = createRemindBookingEmail(user);
    await sendEmail(email);

    let remind_booking_row = find(proxy.t_remind_booking, {
      user_id: user.id!,
    });
    if (remind_booking_row) {
      remind_booking_row.notice_time = Date.now();
    } else {
      proxy.t_remind_booking.push({
        user_id: user.id!,
        notice_time: Date.now(),
      });
    }
  }
}
